In [8]:
#Import numerical libraries
import pandas as pd
import numpy as np

#Import graphical plotting libraries
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

#Import Linear Regression Machine Learning Libraries
from sklearn import preprocessing
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.metrics import r2_score

In [9]:
data=pd.read_csv(r'D:\ds 2\N_Batch -- 4.00PM -- Jun 26\3. Mar 26\6th- l1, l2, scaling\lasso, ridge, elastic net\TASK-22_LASSO,RIDGE/car-mpg.csv')
data

,mpg,cyl,disp,hp,wt,acc,yr,origin,car_type,car_name
0,18.0,8,307.0,130,3504,12.0,70,1,0,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,0,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,0,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,0,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,0,ford torino
...,...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,1,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,1,chevy s-10

In [10]:
data.head()

,mpg,cyl,disp,hp,wt,acc,yr,origin,car_type,car_name
0,18.0,8,307.0,130,3504,12.0,70,1,0,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,0,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,0,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,0,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,0,ford torino

In [11]:
data.tail()

      mpg  cyl   disp  hp    wt   acc  yr  origin  car_type         car_name
393  27.0    4  140.0  86  2790  15.6  82       1         1  ford mustang gl
394  44.0    4   97.0  52  2130  24.6  82       2         1        vw pickup
395  32.0    4  135.0  84  2295  11.6  82       1         1    dodge rampage
396  28.0    4  120.0  79  2625  18.6  82       1         1      ford ranger
397  31.0    4  119.0  82  2720  19.4  82       1         1       chevy s-10

In [15]:
data = data.drop(['car_name'], axis = 1)
data['origin'] = data['origin'].replace({1: 'america', 2: 'europe', 3: 'asia'})
data = pd.get_dummies(data,columns = ['origin'])
data = data.replace('?', np.nan)
data = data.apply(lambda x: x.fillna(x.median()), axis = 0)

KeyError: "['car_name'] not found in axis"

In [16]:
data.head()

,mpg,cyl,disp,hp,wt,acc,yr,car_type,origin_america,origin_asia,origin_europe
0,18.0,8,307.0,130,3504,12.0,70,0,1,0,0
1,15.0,8,350.0,165,3693,11.5,70,0,1,0,0
2,18.0,8,318.0,150,3436,11.0,70,0,1,0,0
3,16.0,8,304.0,150,3433,12.0,70,0,1,0,0
4,17.0,8,302.0,140,3449,10.5,70,0,1,0,0

In [17]:
data

,mpg,cyl,disp,hp,wt,acc,yr,car_type,origin_america,origin_asia,origin_europe
0,18.0,8,307.0,130,3504,12.0,70,0,1,0,0
1,15.0,8,350.0,165,3693,11.5,70,0,1,0,0
2,18.0,8,318.0,150,3436,11.0,70,0,1,0,0
3,16.0,8,304.0,150,3433,12.0,70,0,1,0,0
4,17.0,8,302.0,140,3449,10.5,70,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,1,0,0
394,44.0,4,97.0,52,2130,24.6,82,1,0,0,1
395,32.0,4,135.0,84,2295,11.6,82,1,1,0,0
396,28.0,4,120.0,79,2625,18.6,82,1,1,0,0
397,31.0,4,119.0,82,2720,19.4,82,1,1,0,0

In [18]:
x=data.drop(['mpg'],axis=1)
y=data[['mpg']]

**scaling the data**

In [27]:

x_s=preprocessing.scale(x)
x_s=pd.DataFrame(x_s,columns = x.columns)

In [28]:
y_s=preprocessing.scale(y)
y_s=pd.DataFrame(y_s,columns=y.columns)

In [29]:
x_s

,cyl,disp,hp,wt,acc,yr,car_type,origin_america,origin_asia,origin_europe
0,1.498191,1.090604,0.664133,0.630870,-1.295498,-1.627426,-1.062235,0.773559,-0.497643,-0.461968
1,1.498191,1.503514,1.574594,0.854333,-1.477038,-1.627426,-1.062235,0.773559,-0.497643,-0.461968
2,1.498191,1.196232,1.184397,0.550470,-1.658577,-1.627426,-1.062235,0.773559,-0.497643,-0.461968
3,1.498191,1.061796,1.184397,0.546923,-1.295498,-1.627426,-1.062235,0.773559,-0.497643,-0.461968
4,1.498191,1.042591,0.924265,0.565841,-1.840117,-1.627426,-1.062235,0.773559,-0.497643,-0.461968
...,...,...,...,...,...,...,...,...,...,...
393,-0.856321,-0.513026,-0.480448,-0.213324,0.011586,1.621983,0.941412,0.773559,-0.497643,-0.461968
394,-0.856321,-0.925936,-1.364896,-0.993671,3.279296,1.621983,0.941412,-1.292726,-0.497643,2.164651
395,-0.856321,-0.561039,-0.532474,-0.798585,-1.440730,1.621983,0.941412,0.773559,-0.497643,-0.461968
396,-0.856321,-0.705077,-0.662540,-0.408411,1.100822,1.621983,0.941412,0.773559,-0.497643,-0.461968
397,-0.856321,-0.714680,-0.584501,-0.296088,1.391285,1.621983,0.941412,0.773559,-0.497643,-0.461968

In [30]:
y_s

          mpg
0   -0.706439
1   -1.090751
2   -0.706439
3   -0.962647
4   -0.834543
..        ...
393  0.446497
394  2.624265
395  1.087017
396  0.574601
397  0.958913

[398 rows x 1 columns]

In [31]:
x.head(1)

,cyl,disp,hp,wt,acc,yr,car_type,origin_america,origin_asia,origin_europe
0,8,307.0,130,3504,12.0,70,0,1,0,0

In [32]:
y.head(1)

    mpg
0  18.0

In [33]:
data

,mpg,cyl,disp,hp,wt,acc,yr,car_type,origin_america,origin_asia,origin_europe
0,18.0,8,307.0,130,3504,12.0,70,0,1,0,0
1,15.0,8,350.0,165,3693,11.5,70,0,1,0,0
2,18.0,8,318.0,150,3436,11.0,70,0,1,0,0
3,16.0,8,304.0,150,3433,12.0,70,0,1,0,0
4,17.0,8,302.0,140,3449,10.5,70,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,1,0,0
394,44.0,4,97.0,52,2130,24.6,82,1,0,0,1
395,32.0,4,135.0,84,2295,11.6,82,1,1,0,0
396,28.0,4,120.0,79,2625,18.6,82,1,1,0,0
397,31.0,4,119.0,82,2720,19.4,82,1,1,0,0

In [35]:
x_train, x_test, y_train,y_test = train_test_split(x_s, y_s, test_size = 0.30, random_state = 1)
x_train.shape

(278, 10)

In [36]:
y_train

          mpg
350  1.432898
59  -0.065919
120 -0.578335
12  -1.090751
349  1.356035
..        ...
393  0.446497
255  0.203100
72  -1.090751
235  0.318393
37  -0.706439

[278 rows x 1 columns]

In [37]:
x_test

,cyl,disp,hp,wt,acc,yr,car_type,origin_america,origin_asia,origin_europe
174,0.320935,-0.215346,-0.194303,0.016051,-0.387801,-0.273506,-1.062235,0.773559,-0.497643,-0.461968
359,-0.856321,-0.503423,-0.636527,0.306908,1.754364,1.351199,0.941412,-1.292726,-0.497643,2.164651
250,1.498191,1.196232,0.924265,0.903991,-0.859804,0.538847,-1.062235,0.773559,-0.497643,-0.461968
274,-0.267693,-0.599449,-0.038223,-0.166030,0.120509,0.538847,0.941412,-1.292726,-0.497643,2.164651
283,0.320935,0.370411,-0.376395,0.348290,0.955591,0.809631,-1.062235,0.773559,-0.497643,-0.461968
...,...,...,...,...,...,...,...,...,...,...
382,-0.856321,-0.820308,-0.896659,-0.857702,0.483588,1.621983,0.941412,-1.292726,2.009471,-0.461968
39,1.498191,1.983643,1.834726,1.765921,-1.477038,-1.356642,-1.062235,0.773559,-0.497643,-0.461968
171,-0.856321,-0.570641,-0.220316,-0.317370,-0.750880,-0.273506,0.941412,-1.292726,2.009471,-0.461968
271,-0.856321,-0.359385,0.013803,-0.266530,0.410972,0.538847,0.941412,0.773559,-0.497643,-0.461968
247,-0.856321,-1.041167,-0.896659,-1.064612,1.100822,0.538847,0.941412,-1.292726,2.009471,-0.461968

In [38]:
y_test

          mpg
174 -0.706439
359  0.587411
250 -0.527093
274 -0.411800
283 -0.424610
..        ...
382  1.343225
39  -1.218855
171  0.062185
271 -0.040298
247  2.034986

[120 rows x 1 columns]

In [42]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(278, 10)
(278, 1)
(120, 10)
(120, 1)

In [45]:
print(x_train.isnull().sum())
print(y_train.isnull().sum())

cyl               0
disp              0
hp                5
wt                0
acc               0
yr                0
car_type          0
origin_america    0
origin_asia       0
origin_europe     0
dtype: int64
mpg    0
dtype: int64

In [46]:
x_train = x_train.fillna(x_train.median())
x_test = x_test.fillna(x_train.median())

In [48]:
regression_model = LinearRegression()

regression_model.fit(x_train, y_train)

LinearRegression()

In [49]:
print(y_train.isnull().sum())

mpg    0
dtype: int64

In [51]:
#Fit simple linear model and find coefficients
regression_model = LinearRegression()
regression_model.fit(x_train, y_train)

for idx, col_name in enumerate(x_train.columns):
    print('The coefficient for {} is {}'.format(col_name, regression_model.coef_[0][idx]))
    
intercept = regression_model.intercept_[0]
print('The intercept is {}'.format(intercept))

The coefficient for cyl is 0.32144150841112035
The coefficient for disp is 0.3253770773930386
The coefficient for hp is -0.23247858029588092
The coefficient for wt is -0.7102611174600675
The coefficient for acc is 0.014091422434288826
The coefficient for yr is 0.3754126785346772
The coefficient for car_type is 0.3816901567854053
The coefficient for origin_america is -0.07501956847585714
The coefficient for origin_asia is 0.04481433037434625
The coefficient for origin_europe is 0.048412873782401215
The intercept is 0.017924445674164794

**Ridge L2 Regularization**

In [53]:
ridge_model = Ridge(alpha = 0.3)
ridge_model.fit(x_train, y_train)

print('Ridge model coef: {}'.format(ridge_model.coef_))

Ridge model coef: [ 0.31689029  0.31373985 -0.23199845 -0.7001869   0.01235667  0.37430997
  0.37745075 -0.07453023  0.0447058   0.04790455]

**Lasso L1 Regularization**

In [56]:
lasso_model = Lasso(alpha = 0.1)
lasso_model.fit(x_train, y_train)

print('Lasso model coef: {}'.format(lasso_model.coef_))

Lasso model coef: [-0.         -0.         -0.01344766 -0.52193953  0.          0.28184471
  0.12780319 -0.01622407  0.          0.        ]

In [57]:

#Simple Linear Model
print(regression_model.score(x_train, y_train))
print(regression_model.score(x_test, y_test))

print('*************************')
#Ridge
print(ridge_model.score(x_train, y_train))
print(ridge_model.score(x_test, y_test))

print('*************************')
#Lasso
print(lasso_model.score(x_train, y_train))
print(lasso_model.score(x_test, y_test))

0.8343928169225191
0.8514438048976485
*************************
0.8343775823918624
0.8519929051870808
*************************
0.7937385023352445
0.8374952153130854